on:
  push:
    tags:
      - 'v*'

name: Upload Release Asset
jobs:
  appimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          set -x
          sh -eux tools/build-appimage-container
          ARCH=$(uname -m) sh -ex tools/build-appimage
          assets=()
          for asset in $(find . -name '*.AppImage'); do
            assets+=("$asset")
            bname=$(basename "$asset")
            dname=$(dirname "$asset")
            (cd "$dname" && md5sum "$bname" > "${bname}.md5")
            (cd "$dname" && sha256sum "$bname" > "${bname}.sha256")
          done
          for asset in $(find . -name '*.md5'); do
            assets+=("$asset")
          done
          for asset in $(find . -name '*.sha256'); do
            assets+=("$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          gh release create $tag_name ${assets[@]}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
